export const FETCH_COMPETITIONS = 'POSTS::FetchCompetitions'
export const SHOW_LOADER = 'APP::ShowLoader'
export const HIDE_LOADER = 'APP::HideLoader'
export const FETCH_MATCHES = 'POSTS::FetchMatches'
export const FETCH_TEAMS = 'POSTS::FetchTeams'
export const FETCH_TEAM = 'POSTS::FetchTeam'
export const SHOW_WARNING = 'APP::ShowWarning'
export const HIDE_WARNING = 'APP::HideWarning'
